### ISSUE TITLE
what is check_ver_os command?

### ISSUE THREAD

**Issue by G3NSVRV** [jonretting/geforce-driver-check#1]
G3NSVRV@LAPTOP-S60HCV51 /cygdrive/d/Personal/Downloads/geforce-driver-check
$ check_ver_os
-bash: check_ver_os: command not found

G3NSVRV@LAPTOP-S60HCV51 /cygdrive/d/Personal/Downloads/geforce-driver-check
$ grep check_ver_os geforce.sh
__check_ver_os || __log_error "Unsupported OS Version = $(check_ver_os true)"

**Comment by jonretting** [comment]
func.sh
LIne 121
```
__check_ver_os () {
    [ "$1" = true ] && { wmic os get version /value | grep -Eo '[^=]*$'; return $?; }
    wmic os get version /value | **grep -Eq '6\.[1-3]{1}.*'**
}
```
When I created the utility, I wanted it to be exacting and have plenty of checks. Including one to make sure it was a certain max version of the NT kern. For in stance the command on my Server 2019 box returns 
```
$ wmic os get version /value
Version=10.0.17763
```
All functions like __check_ver_os are sourced from func.sh. You could modify the grep regex to include higher versions, or disable/comment out the check from geforce.sh.
